name: 🧪 Linting
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: Install Dependencies & Run Linter
        run: |
          npm ci
          npm run lint
