name: 🧪 Unit Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: Install Dependencies & Run Tests
        run: |
          npm install
          npm run test
